### ISSUE TITLE
 dc.leafletMarkerChart - popup when mouseover marker

### ISSUE THREAD

**Issue by PBrockmann** [Intellipharm/dc-addons#10]
Popup are opened from a click on a marker.
Is it possible to have popup when mouse is over a marker (mouseover event).

**Comment by Tim-Intellipharm** [comment]
Fixed in commit 731b088688b04088718932189b8ccb4539b4b29f and released in [v0.13.1](https://github.com/Intellipharm/dc-addons/releases/tag/v0.13.1)
