### ISSUE TITLE
dc.leafletMarkerChart - tiles function 

### ISSUE THREAD

**Issue by PBrockmann** [Intellipharm/dc-addons#11]
Is there a tiles function to specify the L.tileLayer and attribution for a dc.leafletMarkerChart ?
It seems but haven't been able to use it.

So to do this, I have changed in hard the code line 25 in dc.leaflet.js

<pre>
var _tiles = function (map) {
            L.tileLayer(
                //'http://services.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{z}/{y}/{x}',
                'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
                {
                    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                    //attribution: 'LSCE &copy; 2016 | Baselayer &copy; ArcGis'
                }
            ).addTo(map);
        };
</pre>

**Comment by Tim-Intellipharm** [comment]
There is a `.tiles()` function in which you can overwrite the default function. This has to be called before the initial rendering.

**Comment by PBrockmann** [comment]
Indeed this function works as you wrote (though a description in the documentation is missing).
Thanks very much.

<pre>
mapChart  = dc.leafletMarkerChart("#chart-map");
mapChart
      .width(1000)
      .height(300)
      .dimension(mapDim)
      .group(mapGroup)
      .mapOptions({maxZoom: mapMaxZoom, zoomControl: false})
      .center([0, 0])  
      .zoom(2)
      .tiles(function(map) {
           return L.tileLayer(
                'http://services.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{z}/{y}/{x}',
                { attribution: 'LSCE &copy; 2016 | Baselayer &copy; ArcGis' }).addTo(map);
       })
</pre>

**Comment by Tim-Intellipharm** [comment]
Updated documentation
