### ISSUE TITLE
dc.leafletMarkerChart - access to popup properties

### ISSUE THREAD

**Issue by PBrockmann** [Intellipharm/dc-addons#13]
How do you access to popup properties ?
I would like to set the marker._popup.options.closeButton to false but cannot access to marker._popup

<pre>
mapChart  = dc.leafletMarkerChart("#chart-map");

mapChart
      .width(1000)
      .height(300)
      .dimension(mapDim)
      .group(mapGroup)
...
      .popup(function(d,marker) {
        console.log(marker);
        //marker._popup.options.closeButton = false;   // not possible
        id = d.key[2] -1;
        return  "Id: " + data[id].Id;
      })
</pre>

**Comment by Tim-Intellipharm** [comment]
Take a look at http://leafletjs.com/reference.html#marker-bindpopup. You can create a popup object and return that and it should work.

**Comment by PBrockmann** [comment]
Indeed, I didn't capture how simple it was. 
So for information, code looks like this:

<pre>
mapChart  = dc.leafletMarkerChart("#chart-map");
mapChart
      .width(1000)
      .height(300)
      .dimension(mapDim)
      .group(mapGroup)
...
      .popup(function(d,marker) {
        id = d.key[2] -1;
        popup = L.popup({autoPan: false, closeButton: false});
        popup.setContent("Id: " + data[id].Id);
        return popup;
      })
</pre>

Thanks
