### ISSUE TITLE
Map dragging broken after clicking on marker

### ISSUE THREAD

**Issue by ktebbe** [Intellipharm/dc-addons#17]
I'm running into the issue where the map won't drag after clicking on a marker. If you click on a marker and then click on the map, it's fine. If you click on a marker and then click "clear filter," it's fine. But if you click on a marker and then zoom, or click on a marker and then drag, or click on a marker and then click the "x" on the pop-up, then dragging stops working. 

 It seems that the problem is coming from the declaration of `y` in `dc-leaflet.min.js` and is saying that `IndexOf is not a function`. Any idea what's causing this?

**Comment by Intellipharm** [comment]
Are you able to create a [plunkr](https://plnkr.co/) replicating the issue

**Comment by ktebbe** [comment]
Unfortunately I cannot. However, if it helps, this is where the error is thrown. Again, the error happens right after I zoom or drag or click the "x." 

![error screen](https://cloud.githubusercontent.com/assets/12629836/16491864/8fe566a0-3ead-11e6-972d-ca1649986243.jpg)

**Comment by Tim-Intellipharm** [comment]
@jasonnance was awesome and found the problem. I have merge in his pull request and this issue should be solved.
