### ISSUE TITLE
leaflet popup broken

### ISSUE THREAD

**Issue by kagesenshi** [Intellipharm/dc-addons#2]
Hi, 

seems like dc.leaflet popup functionality is somehow, broken. Clicking marker does not display a popup.

example page is also affected by it too: http://intellipharm.github.io/dc-addons/examples/leaflet-marker.html

for some reason map._panes.popupPane.appendChild(this._container) in leaflet.js does not add any elements into #leaflet-popup-pane

**Comment by Tim-Intellipharm** [comment]
Fixed in 160449a021fb83cd27cd98e1d1763df399b275d8 and release in [v0.11.3](https://github.com/Intellipharm/dc-addons/releases/tag/v0.11.3)
