### ISSUE TITLE
filter features with  dc.leafletChoroplethChart 

### ISSUE THREAD

**Issue by PBrockmann** [Intellipharm/dc-addons#21]
Is it possible to filter (set visible or not) features displayed from a dc.leafletChoroplethChart ?

I have started to code a small application to filter from specific dimensions different model configurations (here displayed as GeoJSON within a dc.leafletChoroplethChart). But I am stucked on how to link it to a simple row chart for example. Any help welcome.

My code is available from https://github.com/PBrockmann/NEMO_Config_Finder and tested from very last release of dc.js and dc-addons.
![app](https://cloud.githubusercontent.com/assets/5402758/17375429/360ca944-59b1-11e6-9525-2fa556d10c31.png)

**Comment by PBrockmann** [comment]
I have succeed in part.
I can indeed control fillColor with the .colorCalculator but not the style itself (the stroke line for example, I would like to remove or set to 0).

`.colorCalculator(function (d) { if (d.value==0) return "#000"; else return d.Color; })`

Sorry, perhaps more a question to gitter than to gitHub.

**Comment by Tim-Intellipharm** [comment]
There was a recent PR #20 to make leaflet markers change their display if filtered. I think it could be a good option to implement the same kind of logic for the choropleth chart, and make it automatically grey out the areas that have been deselected.

Instead I could change the `colorCalculator` function to `styleCalculator` that would require an object to be returned like 

``` js
.styleCalculator(function(d) {
    return {
        "weight": 3,
        "color": d.Color,
        "opacity": 1,
        "fillColor": d.Color,
        "fillOpacity": 0.3
    };
})

```

**Comment by PBrockmann** [comment]
Yes, the styleCalculator is exactly what I am looking for. 
Great if you can implement it (sorry dc-addons code is quite unclear for my level of js).

I would add that a dc.leafletGeoJSONChart could be created to handle more precisely GeoJSON display. It would be very useful for project such as https://maps.ngdc.noaa.gov/viewers/bathymetry/ that would benefit a lot from dynamic filtering using dc.js and dc-addons.

**Comment by Tim-Intellipharm** [comment]
I have release v0.13.4 with a `featureOptions(feature, v)` function that is available. `colorCalculator` will not work when using this new function.

I am a little confused about your `dc.leafletGeoJSONChart` suggestion because as far as I understand `dc.leafletChoroplethChart` uses geoJson and you should be able to pass any geoJson data you want to it. My expertise is not in geography, so maybe the name `choropleth` is incorrect for the chart

**Comment by PBrockmann** [comment]
Choropleth is a way to represent quantities over areas but GeoJSON can also represent other geographic data structures such as tracks (as in the NOAA beam tracks application). Choropleth might be then not appropriate name in this case. That is why I had proposed to rename dc.leafletChoroplethChart as dc.leafleGeoJSONChart for a more generic scope of use.

I have tested last v0.13.4 for my code and it works nicely: I can change from featureOptions function the features style when they are filtered. 
Note that the distributed example leaflet-choropleth.html does not work anymore.

**Comment by Tim-Intellipharm** [comment]
Would you have any other geoJSON data to test if `dc.leafletChoroplethChart` could be used for any data?

**Comment by PBrockmann** [comment]
Just to point that indeed GeoJSON supports the following geometry types: Point, LineString, Polygon, MultiPoint, MultiLineString, and MultiPolygon.
Representing ship tracks for example is just a matter of changing the type attribut in the GeoJSON
and dc.leafletChoroplethChart is in fact ok to handle this kind of representation. Just the name that is no more accorded to representation of areas (choropleth map from Greek χώρο ("area/region") + πλήθος ("multitude")).

Change in setup.js from https://github.com/PBrockmann/NEMO_Config_Finder
`"geometry": {
                                "type": "Polygon",
                                "coordinates": [d.Coordinates]
                          }`
to
`"geometry": {
                                "type": "LineString",
                                "coordinates": d.Coordinates
                          }`

**Comment by Tim-Intellipharm** [comment]
The leaflet choropleth chart is just using the leaflet geojson functionality (https://github.com/Intellipharm/dc-addons/blob/master/src/scripts/leaflet-choropleth-chart.js#L49).

The leaflet geojson functionality seems to support everything all geojson (http://leafletjs.com/examples/geojson.html).

So if you have some example data I could set up an example and if it works I could rename `dc.leafletChoroplethChart` to `dc.leafletGeoJSONChart`
