### ISSUE TITLE
Tooltip addon standard title removing

### ISSUE THREAD

**Issue by martinkoenig** [Intellipharm/dc-addons#24]
Your function doesn´t remove the original title/tooltip for pie charts. But I´ve found already the solution!
At line 30 in dc-tooltip-mixin.js you have to change "g.pie-slice path" to just "g.pie-slice", after that it work´s like charm.

Best regards und thanks for this great plugin :)

**Comment by Tim-Intellipharm** [comment]
Thanks for finding the fix! Released in v0.13.5
