### ISSUE TITLE
google maps markers areaselect not working propperly

### ISSUE THREAD

**Issue by BioPhoton** [Intellipharm/dc-addons#4]
Hi, 
you lib is awesome!! already stared. :-)

I have a problem.
In you deom [Markers with no clustering and selection by area](http://intellipharm.github.io/dc-addons/examples/google-marker.html) and also in my own tests test filtering works if i move the map. But if i change the pie filter or other connected crossfilter the map flickers and stays the same.

Is it working propperly?

**Comment by Tim-Intellipharm** [comment]
It is definitely an issue. The choropleth on that page doesn't work properly either.

**Comment by Tim-Intellipharm** [comment]
Fixed in commit d2087781e20aef1ffe6825a1c77252c667f80dd9 and released in [v0.11.5](https://github.com/Intellipharm/dc-addons/releases/tag/v0.11.5). Please reopen if the problem persists.

**Comment by BioPhoton** [comment]
Awesome! Thanks for the quick response
