### ISSUE TITLE
Is it possible to create 2 overlays in one map?

### ISSUE THREAD

**Issue by BioPhoton** [Intellipharm/dc-addons#5]
Is it possible to create 2 overlays in one map? 
For example an overlay of markers and another one with path or other markers? 
Could you point me to the right direction for where to start?

**Comment by Tim-Intellipharm** [comment]
I have a case where I need to display a couple of more things in addition to the dc-addons rendered markers. It is important to note that these extra things are seperate to the dc.js library and won't be changed when filtering on other charts.

``` js
// create marker chart
var map_chart = dc.googleMarkerChart('#map'); 

// render the chart
map_chart.options({...}).render(); 

// get the google/leaflet map object
var map = map_chart.map(); 

// get all the markers generated by dc.js from the map. The parameter is whether or not to limit the list to the filtered markers.
var dc_markers = map_chart.markers(true); 

// add a custom marker to the map
var custom_marker = new google.maps.Marker({
    position: map_chart.toLocArray([20, -150]),
    map: map,
    title: 'Custom Marker',
    icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
});
```

Does this help with what you need?

**Comment by BioPhoton** [comment]
Thx for your very quick response!!!

Kind of...

My usecase is to display gps positions in different ways:
- Markers 
- The path of this markers
- A circle for every marker with different radius.

I want to crossfilter the paths circles and markers. 
Goal is to have all 3 as separated layers on one map.

I guess it is somehow similar to stacked area/line-charts...

**Comment by ruhley** [comment]
The only way to currently do that would be to use a event handler to get all the current markers, then add the paths and circles.  - https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#dc.baseMixin+on. The renderlet even is triggered on every crossfilter so it would meet your needs.

However this could be a good time to create a new chart type:

```js
var chart = new googleCustomChart('#chart');

chart
    .dimension(dimension)
    .group(group)
    .width(600)
    .height(600)
    .center([42.69, 25.42])
    .zoom(7)
    .renderItem(function(d, i, map) {
        var marker = new google.maps.Marker({
            position: [d.latitude, d.longitude],
            map: map,
            title: d.name,
            icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
        });
        var circle = new google.maps.Circle({
            position: [d.latitude, d.longitude],
            map: map,
            radius: 5000,
            strokeColor: '#3333AA',
            fillOpacity: 0
        });
    })
    .render();
```

In this chart type you would have to manually draw all the items on the map, but then you get full control over everything and could do whatever you wanted. The ```renderItem``` (is there any other name we could use??) function would be called every time the chart is crossfiltered.

**Comment by Tim-Intellipharm** [comment]
The only way to currently do that would be to use a event handler to get all the current markers, then add the paths and circles.  - https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#dc.baseMixin+on. The renderlet even is triggered on every crossfilter so it would meet your needs.

However this could be a good time to create a new chart type:

``` js
var chart = new googleCustomChart('#chart');

chart
    .dimension(dimension)
    .group(group)
    .width(600)
    .height(600)
    .center([42.69, 25.42])
    .zoom(7)
    .renderItem(function(d, i, map) {
        var marker = new google.maps.Marker({
            position: [d.latitude, d.longitude],
            map: map,
            title: d.name,
            icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
        });
        var circle = new google.maps.Circle({
            position: [d.latitude, d.longitude],
            map: map,
            radius: 5000,
            strokeColor: '#3333AA',
            fillOpacity: 0
        });
    })
    .render();
```

In this chart type you would have to manually draw all the items on the map, but then you get full control over everything and could do whatever you wanted. The `renderItem` (is there any other name we could use??) function would be called every time the chart is crossfiltered.

Would this suit your needs?

**Comment by Tim-Intellipharm** [comment]
I have release v0.12.0 including the new custom charts. See examples at http://intellipharm.github.io/dc-addons/examples/leaflet-custom.html and http://intellipharm.github.io/dc-addons/examples/google-custom.html and http://intellipharm.github.io/dc-addons/#custom-chart has the api of the map.

I will close this issue, hoping that this solution meets your needs. If it doesn't, please just reopen this issue.

**Comment by BioPhoton** [comment]
Hi Tim!

Incredible how fast you response and edit your code. 

THANKS!!!

Will have time next week to test your Code! 
But it looks good for now!
