### ISSUE TITLE
Angular dc and leaflet

### ISSUE THREAD

**Issue by mjvanderveen** [Intellipharm/dc-addons#6]
Hi,

Is it possible to use the dc leaflet library together with the angular-dc library to link charts, tables and maps? Or does it need more work?

**Comment by Tim-Intellipharm** [comment]
@mjvanderveen I have a page with a manually set up `googleMarkerChart` that is linked to some `angular-dc` charts. If they are all using the same crossfilter object it should just work. I haven't tried a google or leaflet chart within `angular-dc`, but I see no reason why it shouldn't work. Are you encountering any issues with it?

**Comment by mjvanderveen** [comment]
Hi Tim, would you be willing to add that example you refer to to the repository, so that I can see it?

**Comment by Tim-Intellipharm** [comment]
I have added an example on the website. Check it out at http://intellipharm.github.io/dc-addons/examples/google-angular.html

As the example works I will close the issue, however if you encounter an problem then reopen it if wish to.

**Comment by mjvanderveen** [comment]
I have got it working, however, I am struggling to access the leaflet Map object in the dc-chart from within the angular controller function, so that I can use a fitBounds() function on the map. Any suggestions how to do that?

**Comment by Tim-Intellipharm** [comment]
Sorry about that but the Angular documentation was a bit out of date. I have updated it to show you how to get the chart object. I have also updated the [example](http://intellipharm.github.io/dc-addons/examples/google-angular.html) to show you how to get the map object.
