### ISSUE TITLE
hexbin.js integrated within dc-addons

### ISSUE THREAD

**Issue by Edouard-Legoupil** [Intellipharm/dc-addons#7]
Would be awesome to integrate as a dc.addons the d3.hexbin. Cf example here: https://bl.ocks.org/mbostock/4248146 

There's a project from @trevorgerhardt   as a source of inspiration: http://trevorgerhardt.com/hexacabi/
https://github.com/trevorgerhardt/hexacabi/blob/gh-pages/index.html#L269:L332

**Comment by Tim-Intellipharm** [comment]
Included in commit c5211c042c912c22d4dd4f603d4e8b9d3ac62d80 and released in [v0.13.0](https://github.com/Intellipharm/dc-addons/releases/tag/v0.13.0).

Please not this is an alpha release and it is still very buggy.
