### ISSUE TITLE
dc.leafletMarkerChart has some missing functions in the documentation

### ISSUE THREAD

**Issue by PBrockmann** [Intellipharm/dc-addons#9]
`.title(function() {})`
that can be used to get rid of the title when mouseover a marker.

`.fitOnRender()` 
that when set to false is usefull to zoom on a specific zone independently of your markers.

**Comment by Tim-Intellipharm** [comment]
Fixed in commit e07cd9490926327f96c1a5ee7d737fb9259027d5 and released in [v0.13.1](https://github.com/Intellipharm/dc-addons/releases/tag/v0.13.1)
